# Generated by Django 5.0.4 on 2024-06-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='services')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('counted_view', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
