# Generated by Django 5.0.4 on 2024-06-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='title',
        ),
    ]
