# Generated by Django 5.0.4 on 2024-06-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_option_service_generals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Category',
            new_name='category',
        ),
    ]
