# Generated by Django 5.0.4 on 2024-06-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_rename_category_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='Category',
        ),
    ]
