# Generated by Django 5.0.4 on 2024-06-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_rename_category_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='generals',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
